#!/bin/bash

source .machines
MANAGER="${MANAGERS[0]}"

IP_MANAGER=`docker-machine ip ${MANAGER}`

eval $(docker-machine env ${MANAGER}) && docker-machine ssh ${MANAGER} -- docker swarm join-token -q manager
