#!/bin/bash

source .machines
MAIN_MANAGER="${MANAGERS[0]}"

IP_MANAGER=`docker-machine ip ${MAIN_MANAGER}`
SWARM_TOKEN=`./swarm-get-token-manager`

for MANAGER in "${MANAGERS[@]}"; do
  echo "[INFO] Attempting to join ${MANAGER} to Docker Swarm manager at ${IP_MANAGER}"
  eval $(docker-machine env ${MANAGER}) && docker-machine ssh ${MANAGER} -- docker swarm join --token ${SWARM_TOKEN} ${IP_MANAGER}:2377
  echo
done

